### ISSUE TITLE
资源管理新增了菜单，权限维护那里看不到

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-boot#10]
<img width="549" alt="image" src="https://github.com/zuihou/lamp-boot/assets/6092525/4c356a34-d815-4907-ac46-2545a73668e0">

<img width="706" alt="image" src="https://github.com/zuihou/lamp-boot/assets/6092525/ae67f592-0295-4a45-a912-6179ca2089f4">
这样我就没法给 新增的菜单配置权限了 ，这是bug吗？

**Comment by zuihou** [comment]
企业版， 新增菜单后，需要在“应用资源授权”，给指定租户授权 才能看到

<img width="946" alt="image" src="https://github.com/user-attachments/assets/f284776d-af4d-4ffa-8a00-90c619b0a666">

**Comment by zqb666** [comment]
> 企业版， 新增菜单后，需要在“应用资源授权”，给指定租户授权 才能看到
> 
> <img alt="image" width="946" src="https://private-user-images.githubusercontent.com/8500410/348446753-f284776d-af4d-4ffa-8a00-90c619b0a666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzM4MTMsIm5iZiI6MTcyMTAzMzUxMywicGF0aCI6Ii84NTAwNDEwLzM0ODQ0Njc1My1mMjg0Nzc2ZC1hZjRkLTRmZmEtOGEwMC05MGM2MTliMGE2NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDg1MTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThmNTMwMGNlZTMzMDUzZjY0YmE5MDMyYTU0ZTJmZWI4YWZkM2ZlNjFiNTdlYzYwNmE0Y2Q4NTU4YzBmOGNkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uZq7fi0ha_4V2ufj0Vno_iX1ZeCHP_4crQhrMV5OKZA">

我用的开源版的 没有看到这个应用授权的菜单

**Comment by zuihou** [comment]
是bug，已修复。
