### ISSUE TITLE
lamp-boot 增加clickhouse数据源配置如果修改？

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-boot#12]
lamp-boot     <version>4.20.0-java17</version>我要增加一个多数据源 clickhouse，这个配置要怎么改 是直接加一个clickhouse的配置
service里加个 @DS("clickhouse") 注解就行了 ，还是需要 改配置？

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/24b29155-1941-46c2-89fa-c3bdbc54b277">

这里的false要改成true吗？
<img width="598" alt="image" src="https://github.com/user-attachments/assets/09a3c39c-37e8-4692-a5ce-160966e39be1">

**Comment by zuihou** [comment]
单体版本，默认不支持增加多数据源。 如有需要可以网上查阅多数据源相关资料或者赞助版的lamp-datasource-max项目进行添加。

**Comment by zqb666** [comment]
> 单体版本，默认不支持增加多数据源。 如有需要可以网上查阅多数据源相关资料或者赞助版的lamp-datasource-max项目进行添加。
我想增加 需要修改什么 如果单独 在spring boot项目做多数据源我知道怎么做 但是基于您的这个配置我不知道怎么修改

**Comment by zqb666** [comment]
<img width="912" alt="image" src="https://github.com/user-attachments/assets/a42b997b-e0cd-4755-94d7-8db39f6add5b">
我把上面的 enabled改成true  项目启动一直报这个错
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/9b2a5abd-259a-4684-ac75-bbf8dcba0f61">

**Comment by zuihou** [comment]
1. spring.datasource.dynamic.enabled= true
2. 加入多数据源相关依赖
3. 增加 spring.datasource.dynamic.xxx 相关的配置，以适配多数据源
