### ISSUE TITLE
boot工程schama模块下，没法找到表

### ISSUE THREAD

**Issue by xswby** [zuihou/zuihou-admin-boot#3]
版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：3.2.3
MySQL(必填)： 5.6
Nacos(必填)：五
其他组件的版本

# 问题描述：
分库没法找到表
### Cause: java.sql.SQLSyntaxErrorException: Table 'lamp_defaults.c_user' doesn't exist

# 报错截图

# 重现步骤
1. 访问了什么接口：
database:
    multiTenantType: SCHEMA
    tenantDatabasePrefix: lamp_base

数据库里建立二个db，并导入lamp_defaults.sql和lamp_base_000.sql
地区表分页列表查询，

**Comment by zuihou** [comment]
地区表单表查询跟 c_user 表没有关联，请提供出错的代码。


报这个错原因是因为执行c_user 这条sql时， ContextUtil.getTenant() 没有获取到租户编码。
