### ISSUE TITLE
前端问题

### ISSUE THREAD

**Issue by 2892931976** [zuihou/zuihou-admin-boot#6]
https://github.com/zuihou/lamp-web-plus 配合哪个后端程序比较简单，感觉比较复杂

**Comment by zuihou** [comment]
lamp-cloud 和 lamp-boot 都行，  

lamp-web-plus 是个人版和企业版才有完整功能， 开源版请看 lamp-web

**Comment by 2892931976** [comment]
lamp-web-plus 个人版和企业版，github地址一样吗？

**Comment by zuihou** [comment]
github 上能找到的，都是开源版

个人版企业版需要购买后，才会还给你
