### ISSUE TITLE
明明设置主键了一只提示 设置主键

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-boot#8]
开源版本 生成代码 
<img width="1389" alt="image" src="https://github.com/zuihou/lamp-boot/assets/6092525/e83385de-96b2-4488-8508-29c7420dc5a0">
<img width="1077" alt="image" src="https://github.com/zuihou/lamp-boot/assets/6092525/abadba43-e5f5-4318-8d2e-fe070d249da2">

**Comment by zuihou** [comment]
表结构脚本发一下

**Comment by zuihou** [comment]
步骤：
1. 建表，设置主键
2. 导入
3. 编辑，填写必填信息
4. 生成或下载代码

我怀疑是你先导入，后在表里面加的主键id。

**Comment by zqb666** [comment]
> 表结构脚本发一下

CREATE TABLE `lamp_none`.`无标题`  (
  `id` bigint NOT NULL COMMENT 'ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `age` int NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

**Comment by zqb666** [comment]
> 步骤：
> 
> 1. 建表，设置主键
> 2. 导入
> 3. 编辑，填写必填信息
> 4. 生成或下载代码
> 
> 我怀疑是你先导入，后在表里面加的主键id。

是的 先导入。提示没有主键。我发现确实忘记设置主键了 然后就去表里加了 但是 还是提示 没有设置主键， 重启服务也不行？ 这好像有点不合理不？

**Comment by zuihou** [comment]
导入时，会将表结构信息存储 表，导入后在修改表结构，并不会直接修改存储的数据。 设计如此，这样的目的是为了防止数据库表被污染。  若修改表结构后，想要生成代码，可以重新导入一次。

**Comment by zqb666** [comment]
> 导入时，会将表结构信息存储 表，导入后在修改表结构，并不会直接修改存储的数据。 设计如此，这样的目的是为了防止数据库表被污染。 若修改表结构后，想要生成代码，可以重新导入一次。

了解了
