### ISSUE TITLE
新建了自己的服务,swagger扫描不到自己福利的接口信息

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-boot#9]
新建了自己的服务，前缀没有lamp，类似 aaa-care
swagger配置：
 - group: 'business'
      displayName: '业务模块'
      paths-to-match: '/**'
      packages-to-scan: top.tangyh.lamp.care
项目重启后swagger文档能看到业务模块的选项，但是 里面看不到任何自己新写的接口文档（基础类都是用的代码生成所以不会是代码上的问题）；
 是不是什么地方的配置要改？  lamp-util里我看有swagger 配置类 作者你会不会swagger扫描的时候写死了 服务必须要lamp前缀？ 如果是这样的 我需要怎么修改配置 才能灵活应用到我的新的服务里swagger接口保证被扫到？

**Comment by zuihou** [comment]
1.   “lamp-util里我看有swagger 配置类” 里面写的是默认值，若yml 中没有配置，则使用此默认值。
2.  在boot-server/pom.xml 加入新建服务的依赖， 然后在yml中加入配置
```
group: 'business'
displayName: '业务模块'
paths-to-match: '/**'
packages-to-scan: 您新建服务的包名

```
